### ISSUE TITLE
[Panel] Improve Pages section sorting via drag'n'drop

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#540]
**Enhancements**
- [x] Split pages section in status segments
- [x] Visualize status segments (make clearer that changing status by dragging to other segment)
- [ ] Handle sections with only one segment
- [x] Handle dragging across different sections (still show segments once dragged over)
- [x] Automatically sorted pages should not be draggable in their segment (listed pages e.g. sorted by date) https://github.com/k-next/starterkit/issues/396
- [x] Drafts and unlisted pages should not be draggable in their segment https://github.com/k-next/starterkit/issues/396
- [x] Visualize which items are draggable https://github.com/k-next/starterkit/issues/380
- [x] Visualize which segments are sortable https://github.com/k-next/starterkit/issues/380
- [ ] Status icon: full opacity, dim when e.g. draft can't yet be published https://github.com/k-next/starterkit/issues/539
- [ ] Ensure it also works for cards view

**Fixes**
- [ ] Ensure droppable sections/segments are clearly indicated at all times https://github.com/k-next/starterkit/issues/450
- [x] Fix dropping back last item which has been dragged away https://github.com/k-next/starterkit/issues/449
